_wandb:
    value:
        cli_version: 0.22.2
        e:
            3n7ybrmez4tfgvicwydmx1ldqouiiwkd:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "2147483648"
                args:
                    - --config
                    - configs/concentration.yaml
                codePath: .venv/bin/alt-back-train
                codePathLocal: .venv/bin/alt-back-train
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "219375939584"
                email: danielthomward@gmail.com
                executable: /Users/danburke-ward/Outside/alt_back/.venv/bin/python3
                git:
                    commit: f6cc600a49cf4bd76184ab48626fae47bc2ae195
                    remote: https://github.com/tick143/fmnist_base.git
                host: MacBookAir
                memory:
                    total: "8589934592"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/danburke-ward/Outside/alt_back/.venv/bin/alt-back-train
                python: CPython 3.11.12
                root: /Users/danburke-ward/Outside/alt_back
                startedAt: "2025-10-20T17:03:18.658237Z"
                writerId: 3n7ybrmez4tfgvicwydmx1ldqouiiwkd
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.12
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
backward:
    value:
        params:
            concentration_momentum: 0.85
            energy_momentum: 0.9
            energy_slope: 1.4
            loss_tolerance: 1e-05
            push_rate: 0.08
            step_scale: 0.015
            suppress_rate: 0.05
            weight_clamp: 6.5
        target: alt_back.backward.concentration.ConcentrationGradientBackwardStrategy
dataset:
    value:
        download: true
        root: ./data
        target: null
model:
    value:
        target: alt_back.models.simple.SimpleFashionCNN
optimizer:
    value:
        params:
            lr: 0.001
            optimizer_class: torch.optim.Adam
        target: alt_back.optim.null_optimizer.NullOptimizerStrategy
training:
    value:
        batch_size: 128
        device: auto
        epochs: 5
        log_interval: 100
        num_workers: 2
        seed: 42
