_wandb:
    value:
        cli_version: 0.22.2
        e:
            4kl2iilkn85cud2b8ouiakwxmp3wal0i:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                args:
                    - --config
                    - configs/cofire.yaml
                codePath: .venv/bin/alt-back-train
                codePathLocal: .venv/bin/alt-back-train
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "220419207168"
                email: danielthomward@gmail.com
                executable: /Users/danburke-ward/Outside/alt_back/.venv/bin/python
                git:
                    commit: 64f734433fdfd4a4d7d2be568a5deec8a34f2125
                    remote: https://github.com/tick143/fmnist_base.git
                host: MacBookAir
                memory:
                    total: "8589934592"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/danburke-ward/Outside/alt_back/.venv/bin/alt-back-train
                python: CPython 3.11.12
                root: /Users/danburke-ward/Outside/alt_back
                startedAt: "2025-10-19T16:33:18.438175Z"
                writerId: 4kl2iilkn85cud2b8ouiakwxmp3wal0i
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.12
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
backward:
    value:
        params:
            clamp_penalty: 0.05
            clamp_value: 4
            entropy_weight: 1
            lr: 1
        target: alt_back.backward.cofire.CoFireBackwardStrategy
dataset:
    value:
        download: true
        root: ./data
model:
    value:
        params:
            dropout: 0.2
            hidden_layers:
                - 512
                - 256
        target: alt_back.models.mlp.FashionMLP
optimizer:
    value:
        params:
            lr: 0.01
            optimizer_class: torch.optim.SGD
        target: alt_back.optim.torch_optimizer.TorchOptimizerStrategy
training:
    value:
        batch_size: 128
        device: auto
        epochs: 5
        log_interval: 100
        num_workers: 4
        seed: 42
