training:
  epochs: 100
  batch_size: 128
  log_interval: 200
  device: auto
  seed: 42
  num_workers: 4

dataset:
  target: alt_back.data.fashion.dataloaders
  params:
    root: ./data
    download: true
    augmentations:
      random_rotation: 10
      normalize:
        mean: [0.5]
        std: [0.5]

model:
  target: alt_back.models.mlp.FashionMLP
  params:
    hidden_layers: [512, 256]
    dropout: 0.2

backward:
  target: alt_back.backward.minimal_credit_field.MinimalCreditFieldBackwardStrategy
  params:
    eta: 0.3
    mu: 0.6
    sigma: 5.0
    inhib: 0.1
    reward_budget: 1.0
    loss_tau: 0.98
    reward_mode: accuracy

optimizer:
  target: alt_back.optim.null_optimizer.NullOptimizerStrategy
  params: {}

logging:
  enabled: true
  project: alt-back
  run_name: fashion-mlp-mcf
  tags: ["fashion-mnist", "mlp", "minimal-credit-field", "gradient-free"]
