training:
  epochs: 100
  batch_size: 128
  log_interval: 200
  device: auto
  seed: 42
  num_workers: 4

dataset:
  target: alt_back.data.fashion.dataloaders
  params:
    root: ./data
    download: true
    augmentations:
      random_rotation: 10
      normalize:
        mean: [0.5]
        std: [0.5]

model:
  target: alt_back.models.spiking.TinySpikingNetwork
  params:
    input_neurons: 784
    hidden_layers: [256, 256, 256]
    output_neurons: 10
    spike_threshold: 0.0
    spike_temperature: 0.3

backward:
  target: alt_back.backward.concentration.ConcentrationGradientBackwardStrategy
  params:
    push_rate: 0.3
    suppress_rate: 0.05
    step_scale: 1
    energy_slope: 1.4
    energy_momentum: 0.5
    concentration_momentum: 1.4
    loss_tolerance: 1e-5
    weight_clamp: 6.5
    direction_mode: outputs_minus_inputs

optimizer:
  target: alt_back.optim.null_optimizer.NullOptimizerStrategy
  params: {}

logging:
  enabled: true
  project: alt-back
  run_name: fashion-spiking-concentration
  tags: ["fashion-mnist", "spiking", "concentration", "gradient-free"]
