training:
  epochs: 5
  batch_size: 128
  log_interval: 100
  device: auto
  seed: 42

dataset:
  root: ./data
  download: true

model:
  target: alt_back.models.simple.SimpleFashionCNN

backward:
  target: alt_back.backward.mass_redistribution.MassRedistributionBackwardStrategy
  params:
    release_rate: 0.3
    reward_gain: 0.8
    base_release: 0.05
    decay: 0.1
    temperature: 0.9
    efficiency_bonus: 0.5
    column_competition: 0.4
    noise_std: 0.02
    mass_budget: 6.0
    signed_weights: true
    enable_target_bonus: true
    target_gain: 0.6
    affinity_strength: 0.1
    affinity_decay: 0.99
    affinity_temperature: 1.5



optimizer:
  target: alt_back.optim.null_optimizer.NullOptimizerStrategy

logging:
  enabled: true
  project: alt-back
  run_name: mass-redistribution-demo
  tags: ["mass-redistribution", "bio"]
  log_logits: true
  log_probabilities: true
  log_entropies: true
